### ISSUE TITLE
[Feature] File Renamer

### ISSUE THREAD

**Issue by Atlas2142** [stashapp/stash-box#131]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem but is rather a request for a feature that would greatly improve Stash's usability as a database tool. I am requesting a file renamer for the Stash utility.

**Describe the solution you'd like**
I would like to see a file renamer for Stash, ideally accessible from the scene list, or within the edit screen for individual scenes. This renamer would allow you to select the variables you want to use for renaming (i.e. scene name, performer, year, etc.) and then when you select "rename" it will rename the file in the windows explorer folder where the file is stored. Ideally, this would also create a subfolder with the same name and place the scene file in the subfolder. Think of TinyMediaManager's Rename and Cleanup feature.

**Describe alternatives you've considered**
We could do this manually, but for someone with a large collection, this would be extremely time-consuming and a rename/cleanup for files would be super helpful.

**Comment by Atlas2142** [comment]
Additionally, it would also be awesome if for movies, each scene labeled with the specific movie could be ordered and placed in a subfolder with the scene title that would be placed within a subfolder for the movie title. Just a thought.

**Comment by ferengi82** [comment]
do you know the scripts/plugins? they have no gui button, but it works realy well

https://github.com/stashapp/CommunityScripts/tree/main/plugins/renamerOnUpdate

https://github.com/stashapp/CommunityScripts/tree/main/scripts/Sqlite_Renamer

**Comment by WithoutPants** [comment]
I'd suggest looking at the stash repository - this is stash-box and is off topic here.
