### ISSUE TITLE
[RFC] Automating disambiguation

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash-box#239]
### Scope
Creating performer disambiguation is currently a manual process dependent wholly on the editor. It adds extra layers of work that may or may not be performed. Can we automate this process?

##  Problem
Automatically scraping in new performers, creating one manually, or modifying an existing performer name, adds the possibility of duplicate name collisions -- an unavoidable problem. The solution is manually creating a disambiguation field. However, this presents some points of failure and extra work:

1. Performer creation or primary name modification
   A. The user should remember to query for the primary name to determine if it already exists. If yes, create/update the disambiguation field.
2. Primary name modification with an already existing disambiguation field
   A. Refer to step 1A
   B. If step A yields no results, remember to remove disambiguation
   C. The user should query the existing incumbent primary name. If there is only one other duplicate of the incumbent name, should the user remove disambiguation from that other performer since there will no longer be duplicate names? Who knows what a user will do.
3. Creating disambiguation
   A. How does a user decide what to use? What he thinks is relevant, may not actually be relevant
   B. Since this process is arbitrary, there is a lack of consistency throughout disambiguation fields
   C. The user may choose to disambiguate based on birth year, country, or any other existing attribute. If said attribute ever requires modification, future editors will have to remember to modify their reference in the disambiguation field as well

We could create guides/best practices for this, but we're adding complexity, and still relying on an editor to check a guide and implement what he's read, assuming he understood it.

##  Proposal
We can avoid all of this by implementing automatic disambiguation creation for every performer that is created or has their records modified. 

### Disambiguation variables
What information is generally relevant to a user who is querying a performer, and what information generally differentiates them from another performer with the same primary name (aside from an image)?

This is a proposed hierarchy of variables to use for disambiguation:
1. Performer aliases
   - `Primary name (aliases)` --> `Svetlana (Sveta, Veronica, Maria Q)`
   - Both indexxx.com and iafd.com use aliases as the main disambiguating factor. Why? I suspect users are more familiar with a performer's aliases than their birthdate or nationality. Often when querying, they could be querying an alias of the primary name.
   - Duplicate single name performers often share the same nationality (see this list of [Svetlana's](https://www.indexxx.com/search/?query=svetlana); how many are Russian? Plenty.), the combination of a performer's aliases are usually unique to that performer.
2. Birthdate and nationality
   - `Primary name (b. yyyy-mm-dd,  nationality)` --> `Svetlana (b. 1999-05-05, RU)`
   - Failing a lack of any aliases available, use the birthdate and country fields together
   - When a death date is implemented it can be incorporated into the disambiguation
     - `Primary name (birth year-date year, nationality)` --> `Svetlana (1999-2022, RU)`
3. Failing birthdate AND nationality field, use either birthdate OR nationality (which ever field is available)
   - `Primary name (b. yyyy-mm-dd)` --> `Svetlana (b. 1999-05-05)`
   - `Primary name (nationality)` --> `Svetlana (RU)`
   - Nationality alone as a disambiguating variable isn't very good as mentioned above, but at this point the performer's metadata is thin. Performer's with similar first names tend to be from the same geographical regions. Performer's with Hungarian names tend to be Hungarian, Russian performer names tend to be from Russia, etc.
4. Failing that use ethnicity and gender
   - `Primary name (ethnicity gender)` --> `Svetlana (White Female)`
   - This isn't going to be very differentiating in most cases. If we use the list of Svetlana's as our example, most will all return `White Female`, with maybe a few `Black Female` or transgender outliers. Also, ethnicity can sometimes be an arbitrary field and may not be accurate (such as Latin, Mixed, etc).
5. Failing that, no disambiguation is generated
   - If a performer lacks metadata, no relevant disambiguation can be generated

In the future, if an alias + studio association is ever implemented, such as indexxx alias-studio association, we can use a performer's studio as a disambiguation factor, and decide where in the hierarchy it is used

**Comment by Tweeticoats** [comment]
Having both a generated disambiguation string and an auto generated one as an option might be a good idea.
If the disambiguation string is currently set to null have stashdb automatically generate this string on the fly and display that instead.
Someone can freeze this string by editing the performer and setting this string.
When editing the performer there could be given options, save a custom string, save this back to null or save the automatically generated string as the current disambiguation freezing this in the database.
