### ISSUE TITLE
[Feature] Disallow the submission of duplicate scenes and duplicate pending scenes.

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash-box#282]
**Is your feature request related to a problem?**
In the current version, it is possible to submit scenes that have the same title, performers and description as existing scenes in stashbox. It is also possible to submit duplicates of pending scenes. Indeed, someone submitted the same scene as I had submitted a couple of hours before the other person. Ironically, my submission was down voted, because the later submission was accepted first, which led me to be wrongly accused of submitting a duplicate.

**Describe the solution you'd like**
On the first page of the scene submission wizard, return an error stating that there already exists a scene by the same name. The same should be true for submitting a duplicate draft, perhaps provide a link to the pending submission, so that you can vote it in.

**Describe alternatives you've considered**
The alternative is to let everyone check their submissions manually which is prone to human error.

**Comment by VonTittyslappen** [comment]
Yeah, this ought to be a priority now that the gates have been opened, the search is not picking up some results which doesnt help either so having this step to warn people about the scene possibly already existing, is a necessary step

**Comment by WithoutPants** [comment]
Bounty added for $10.

**Comment by VonTittyslappen** [comment]
> Bounty added for $10.

Nice, you added the bounty or someone else did and you're posting it here? :)

**Comment by WithoutPants** [comment]
kronkels did.

**Comment by Flashy78** [comment]
I believe this has been implemented already, and it will check existing/pending submissions that have the same title or phash.

**Comment by WithoutPants** [comment]
Resolved by #502

**Comment by WithoutPants** [comment]
@InfiniteStash let me know what you want to do with this bounty.
