### ISSUE TITLE
[Feature] Add a notification system to stash-box

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash-box#284]
**Is your feature request related to a problem?**
It's hard to keep track of comments to your edits right now, you have to manually monitor your edits for comments and down votes.

**Describe the solution you'd like**
Add a notification system, notify when someone comments on your edit, when someone (down) votes your edit, and optionally when your edit gets accepted.

**Describe alternatives you've considered**
Manually monitoring the edits, which is tedious.

**Comment by ghost** [comment]
> and optionally when your edit gets accepted.

All notifications should be optional and let you choose between website, email or both.

**Comment by WithoutPants** [comment]
$10 bounty placed (@DogmaDragon redirected from [#673244](https://opencollective.com/stashapp/contributions/673244)).

**Comment by WithoutPants** [comment]
$65 bounty placed ([#678558](https://opencollective.com/stashapp/contributions/678558))

Total bounty $75.

**Comment by echo6ix** [comment]
An idea of how this could look on the navbar here https://github.com/stashapp/stash-box/issues/512

**Comment by echo6ix** [comment]
Advocating the inclusion of [Push API](https://www.w3.org/TR/push-api/) [web browser] notifications[^a] [^b] to this notification system. I'm assuming email notifications might be an obvious choice, but given the nature of the content some  users might want to avoid that. 

[^a]:https://www.w3.org/TR/push-api/
[^b]:https://support.mozilla.org/en-US/kb/push-notifications-firefox
