### ISSUE TITLE
[Bug Report] add Non-binary as an option for genders

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash-box#297]
**Describe the bug**
Currently the list of genders is: Unknown, Female, Male, TransFemale, TransMale and intersex.
Non-binary does not exist in an option in stash-box but is an option in stash.

**Additional context**
Are there other genders we need to consider?
Might be worth asking for suggestions on what we should store

**Comment by Flashy78** [comment]
This can be closed.
