### ISSUE TITLE
[Feature] Disallow the submission of scenes without performers

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash-box#298]
**Is your feature request related to a problem?**
Scenes can be added without any performers attached to them. This leads to a tsunami of new scenes without any performers attached to them.

**Describe the solution you'd like**
The scene creation wizard should disallow the creation scenes without any performers attached to them. If there are any studios that don't list performers, the democracy may add an exception on a per studio basis requiring a certain amount of votes, but those are fringe  nonetheless.

**Comment by ghost** [comment]
This is a question for guidelines, not stash-box itself.
