### ISSUE TITLE
[Bug Report] Upvoting a +2 edit on a performer page crashes the page

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash-box#305]
**Describe the bug**
When on a performer page with a pending edit with +2 votes, adding one more upvote will make the page crash. All components will disappear and only the background color will remain.

**To Reproduce**
1. Go to a performer page with a pending edit with +2 votes.
2. Vote 'Yes' on the edit, causing the edit to get accepted.

**Expected behavior**
The page should refresh and show the patched performer.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 96

![Schermafdruk_2022-02-12_17-44-01](https://user-images.githubusercontent.com/92669709/153720324-1476e1bd-0536-4612-93c1-14a1327245c0.png)

**Comment by peolic** [comment]
my guess would be because the first image was removed in that edit.

**Comment by ghost** [comment]
Pretty sure this was fixed a while ago.
