### ISSUE TITLE
Congratulations and question about undefined/null in input

### ISSUE THREAD

**Issue by frederikhors** [stashapp/stash-box#34]
Hi guys! Your project is crazy awesome!

I'm new to Go and Gqlgen (an hobby, not a job) and I'm having a hard time with this: https://github.com/99designs/gqlgen/issues/866.

Basically: how to distinguish presence from nil (undefined vs null) in an Input type.

Gqlgen suggests to use `mapstructure` here: https://gqlgen.com/reference/changesets/.

How are you doing? Are you doing it?

Thanks for your amazing work! ❤️

**Comment by ghost** [comment]
@frederikhors Sorry about the late reply. This project does not yet use changesets. The sister project, stash, has added that however. See https://github.com/stashapp/stash/pull/976
