### ISSUE TITLE
[RFC] Scene Draft Link should always be Studio

### ISSUE THREAD

**Issue by cytec** [stashapp/stash-box#343]
### Scope
When publishing a new Draft from within Stash the Link provided by Stash should always be flagged as Studio Link.

##  Long Form
Since stash-box supports multiple URL Types per Scene and stash (at least currently does not) the submitted URL when pushing a draft to stash-box should always be set to `STUDIO`. 

I've created a lot of Scenes lately and a most of them where from ManyVids Sub-Studios. Thats where i scraped the Info from. I've Submitted all of them only to realize that the Link (in the stash URL Field) was automatically set to ManyVids (which would be ok for me if it was at least editable) and can't be changed or set to studio. I didn't really bother about that until i found out that only the `Studio` Type is handled by stash resulting in the URL getting deleted if re-scraped from stash-box

## Examples
![Bildschirmfoto 2022-03-30 um 12 19 57](https://user-images.githubusercontent.com/1104903/160809752-9174e7ec-bcf7-4bdc-8518-b462300284bd.png)
Here is an example of the edit Draft view with the URL Set to `Manyvids` automaticly

**Comment by Flashy78** [comment]
Rather than change the behavior of Stash-box, which isn't actually incorrect, I've made a PR to Stashapp to look for a URL beyond Studio, which should fix the problem in Tagger.
https://github.com/stashapp/stash/pull/3439
