### ISSUE TITLE
[Feature] Production Dates

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash-box#346]
**Is your feature request related to a problem? Please describe.**
When it comes to scene release dates, it seems that users are most interested in making sure the date allows Stash to accurately reflect the ages of the performers in the scene (from my unscientific observations on Discord). This often causes contributors to prefer dates that aren't a scene's actual release date when it comes to remasters, re-releases, redistributions, DVD releases, etc. Ultimately, what these users want is for ages to be calculated according to a date closest to the scene's actual day of filming, rather than the day it's publicly released. This would be the scene's official Date of Production, or at least our closest approximation to it since DOPs aren't always publicly listed.

**Describe the solution you'd like**
Allowing for a secondary date field in Stash-Box for Production Date alongside the current Release Date. This will provide a source for more accurately calculating performer ages while still preserving scenes' actual release dates. Some studios list the official DOPs in the production slates at the start of their videos, on the back of DVD covers, or sometimes embedded in the original filenames. For studios that don't publicly list DOPs, they can often be approximated by examining embedded metadata in officially released video files and image galleries. Cast and crew from a production will sometimes post about a scene on the day of production as well, but these examples will likely be difficult to source. For remasters/re-releases/redistributions, the release date of the original scene would suffice as well.

**Describe alternatives you've considered**
A related feature request that has come up on Discord often is support for release groups, organized similarly to MusicBrainz. This could allow for more elegant handling of duplicate releases in Stash-Box by linking scene entries together with a prominent "canonical" entry for the original release. Non-canonical releases could maintain their unique information (including release dates) while inheriting the canonical entry's date as an "Original Release Date". This would obviously require a much larger overhaul of both Stash and Stash-Box to accomplish and will require it's own separate feature request on GitHub.

**Comment by echo6ix** [comment]
+1 for [Release Groups](https://musicbrainz.org/doc/Release_Group) ala MusicBrainz.

Also StashDB currently doesn't support non-web scene movies, but a lot of older web scenes are derivative of a scene from a movie DVD release. Any implementation of Release Groups would need to take that into consideration.
