### ISSUE TITLE
[Bug] Unable to delete studios with hidden (deleted) scenes

### ISSUE THREAD

**Issue by peolic** [stashapp/stash-box#361]
**Update:** Looks like this is the code that gets executed when the `studio destroy` edit gets applied, though I still don't understand why it fails. Last I checked this issue locally, I was able to delete a studio with deleted scenes without any issue.
Maybe I missed a step in trying this out, maybe there's a dirty sql schema on production?
https://github.com/stashapp/stash-box/blob/c469f7f9afb3f1ad36492c677d5cd6570aea7f2e/pkg/sqlx/querybuilder_studio.go#L487-L493

---

This was discussed on Discord a few times following edit application failures.

Example:
Studio "A" has 2 scenes,
the first scene is moved to studio "B",
and the second scene is a duplicate of an existing scene from studio "B", and therefore deleted.

The deleted scene is of course only "soft-deleted" and remains attached to the now-seemingly-empty studio "A" under the hood.
Deleting studio "A" results in a failed edit:
```
Edit application failed:

Unknown Error: Error executing query: UPDATE scenes SET studio_id = NULL WHERE studio_id = ?, 
with args: [<studio id>]: pq: null value in column "studio_id" of relation "scenes" violates not-null constraint
```

P.S.
studios for deletion have been grouped under studio ID: `b32fa427-3d3f-4386-80ad-561c004c8248`

**Comment by ghost** [comment]
As peolic suspected, it turned out to be a dirty schema in production.
