### ISSUE TITLE
[Feature] Store config in home directory

### ISSUE THREAD

**Issue by djarbz** [stashapp/stash-box#37]
**Is your feature request related to a problem? Please describe.**
Running on Linux, I install binaries in /usr/local/bin.
The running user does not have access to write to this folder, nor should it.

**Describe the solution you'd like**
I would like to see the config folder be placed in ~/.config/stashbox

**Comment by WithoutPants** [comment]
You can specify the location of the config file from the command line with `--config_file <config file path>` (ie `--config_file ~/.config/stashbox/config.yml`). 

By default, stash-box writes the config file in the current working directory, so you can run it from the directory where you want your config to be stored. Shouldn't matter where the binary is installed.

Closing this as largely already met. Please comment further if you need more information.
