### ISSUE TITLE
[Feature] Allow scene/performer/etc update calls to only effect specified fields.

### ISSUE THREAD

**Issue by mmenanno** [stashapp/stash-box#446]
**Is your feature request related to a problem? Please describe.**
When updating a scene, performer, etc via an update call to the API, fields that were not included in the API call will be written as null. This leads to `update` actions for stash-ids from stash, as well as update calls from community written scripts, being unintentionally destructive, and having to write in behaviour to pre-fetch data.

For example a graphql call like this:
```GraphQL
mutation Scenes($input: SceneEditInput!) {
  sceneEdit(input: $input) {
    id
    director
  } 
}
```

With variables:
```Json
{
  "input": {
    "edit": {
      "id": "f5460608-3f3c-4108-96e1-2c078e868949",
      "operation": "MODIFY",
      "comment": "add director"
    },
    "details": {
      "director": "Laurent Sky"
    }
  }
}
```

should be expected to create an edit for the scene changing or adding only the director field. However it will delete every other field attached to the scene. 

**Describe the solution you'd like**
Update calls to scenes, performers, etc, should not be destructive to fields not included in the update call. There needs to be a way to specify that data should be merged instead of nullified, but also a way to nullify it when that is the actual intention (which is more rare)

**Describe alternatives you've considered**
If we would like to preserve the behaviour of how this endpoint operates, then another endpoint should be added.

**Additional context**
The differences between Stash and stash-box's data models become very evident with this issue, as updating a scene for instance will always delete any properties stash doesn't currently have like studio codes and directors. As well as ones where their capabilities aren't mirrored like links where stash only supports one link, so an update submission will delete additional links.

**Comment by scruffynerf** [comment]
In the short term, until Stash catches up with the Stash-box field structures, I suggest any edits done this way be 'additive' only.  That would prevent the problem, and keep it useful.

**Comment by mmenanno** [comment]
Equivalent stash side change here https://github.com/stashapp/stash/pull/976
