### ISSUE TITLE
[RFC] Different sign up process for main instance

### ISSUE THREAD

**Issue by milkyshakes** [stashapp/stash-box#460]
*### Scope*

Avoid using Discord for access to the main stash-box instance.

## Examples
Discord for me won't work unless I give them my number and they're not the most private platform. Considering this is an open source project there should be alternatives. Any chances we might get a matrix space?

**Comment by Leopere** [comment]
We’ve honestly been discussing this for ages. I’d prefer to use our own instance so we’re not stuck doing yet another migration in the future. We’re just debating the best way to set one up. It may not be soon. But there’s an increasing sense of urgency developing on the matter so it may be sooner than later.

**Comment by DogmaDragon** [comment]
We opened a Matrix community. 

Our official space is located at `#stashapp:unredacted.org`. 
Invite link: https://matrix.to/#/#stashapp:unredacted.org

**Comment by Leopere** [comment]
@DogmaDragon can you update the respective documentation to reflect the shift toward matrix > discord? Then someone can close this ticket.
