### ISSUE TITLE
[Feature] Field locking to prevent future edits (ie. for release date) on StashDB

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash-box#464]
**Is your feature request related to a problem? Please describe.**
We were on Voice Chat in the Discord earlier today and discussed adding an option to StashDB for fields to be locked from editing, a bit like how Plex locks work. One reason for this is because of release dates from studios being adjusted constantly (a dirty tactic from studios to make their site look more active than it actually is).

Once data is really confirmed without doubt, the fields can be locked from editing, this will prevent a very long game of tennis where people keep submitting edits to a scene that is actually 100% correct.

Another example of this is where people mistakenly edit an original scene entry and change the release date to the date of a remaster.

**Describe the solution you'd like**
Plex like function where lock icons appear next to the fields, to lock the data from being edited (obviously a function to unlock would be required too).

Further discussions in the VC suggested that a form of moderator role on StashDB would be good so that only moderators/admins can approve the locking of fields from editing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by echo6ix** [comment]
Duplicate of https://github.com/stashapp/stash-box/issues/213

**Comment by AdultSun** [comment]
Gah, one second faster than me.

**Comment by VonTittyslappen** [comment]
Oops, thanks guys :)
