### ISSUE TITLE
[Bug Report] Bug adding Eurobabeindex link to performer

### ISSUE THREAD

**Issue by Emilo2** [stashapp/stash-box#473]
**Describe the bug**
Adding Eurobabeindex link to a performer appends extra characters to the end making the link invalid.

**To Reproduce**
1. Go to 'Edit performer'
3. Add Eurobabeindex link on the 'Links' page
4. Observe the link being appended "www." to the end of the link

**Expected behavior**
Link should be left as is

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browsers: Chrome 103.0.5060.134, Safari 15.5 (17613.2.7.1.8)
 - OS: Arch Linux
 - Browser: Chromium 103.0.5060.114

**Comment by Emilo2** [comment]
This issue has been fixed.

**Comment by peolic** [comment]
you can close the issue then
