### ISSUE TITLE
[Feature] Add a performers nav-tab on studio pages

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash-box#483]
On the studio page it would be very helpful (for identification purposes among others) to see all performers associated with said studio.

**Describe the solution you'd like**
Add a *Performers* nav-tab that shows the default performers thumbnail layout consisting of every performer attached to a scene associated with the studio.

Here's a typical use-case where this is helpful for me: performers, especially male, often have recurring roles with a studio, and they're also often uncredited. Seeing a list of male performers for the studio would make the visual identification process a lot easier when submitting or completing missing performers for scenes.

(A dirty concept)

![image](https://user-images.githubusercontent.com/37937507/197422196-e1666578-eaca-47b3-b4f4-deca5ea2fada.png)

**Comment by AnonTester** [comment]
On the individual performers page we can filter by studio already, but on studios we can not filter by performer. On the Scenes page we cannot filter at all. To unify the interface and options, all pages should have filter options by performer, scenes, studio, tag and relevant page name to be able to drill down and find entries easier.
Thanks.
