### ISSUE TITLE
[Bug] Update aliases checkbox reset when updating edit

### ISSUE THREAD

**Issue by peolic** [stashapp/stash-box#493]
'Set performance aliases to old name' checkbox is reset to its initial value when updating an edit.
Initial value being [the "has the name changed" check and `useEffect` inside the component](https://github.com/stashapp/stash-box/blob/v0.2.7/frontend/src/pages/performers/performerForm/PerformerForm.tsx#L191-L198).
This is because it is not passed down as a prop to `PerformerForm`, and not integrated into the logic.
[I attempted to fix this](https://github.com/peolic/stash-box/commit/0ebcff3d00aa01339b529e33ea5b9ab9fb1ea923), but couldn't figure out the solution.

![image](https://user-images.githubusercontent.com/66393006/188727640-9feeb358-e471-46da-b574-2140bb9ba4d3.png)
![image](https://user-images.githubusercontent.com/66393006/188727808-48a46f3d-ef79-4b4b-b18c-60394e18fcd5.png)

**Comment by InfiniteStash** [comment]
The solution to dealing with `useEffect` is usually just removing it. In this case it was the equivalent of `defaultValue={true}` for the checkbox, which is dumb.

**Comment by peolic** [comment]
IIRC the point of it was to change the checkbox value when the name changes, but it's been a while so maybe not.

**Comment by peolic** [comment]
> IIRC the point of it was to change the checkbox value when the name changes, but it's been a while so maybe not.

Looks like now when renaming a performer, "Set unset performance aliases to old name" is not checked by default.
Seems to be confusing to editors since it was enabled by default for a long time.

That buggy code was my doing - #271
> **_Check update aliases by default on performer rename:_**
	Like the first commit above, this has been confusing.
	It seems most edits do need it enabled, you only need to uncheck this on rare occasions (as said, typos).
	Implementation detail - In order for the form callback to not send this value as true when the name isn't changed I opted to use `useEffect` instead of changing the default state to true. It works, but if you have a better idea, go for it.

**Comment by InfiniteStash** [comment]
> IIRC the point of it was to change the checkbox value when the name changes, but it's been a while so maybe not.

The useEffect is superfluous since it would only ever be triggered when the performer name was changed, in other words it always evaluated to true, and thus screwed up edit updates. By just setting `defaultChecked={options?.set_modify_aliases ?? true}` it will use the previously set state, or true. My mistake was setting the fallback to false.
