### ISSUE TITLE
[Bug Report] Instructions are unclear?

### ISSUE THREAD

**Issue by jazzgott** [stashapp/stash-box#51]
Been trying to install this for the nth time today. I try to follow the instruction, but:

yarn install --frozen-lockfile
gets me only
yarn: error: no such option: --frozen-lockfile

That's the first issue
then when I go to /opt/stash-box and try to run 
make generate
everything is fine, but as soon as I try to run 

make ui build

I get 

root@stashbox:/opt/stash-box# make ui build
cd frontend && yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
make: *** [Makefile:112: ui-only] Error 1

which now when I look at it seem like some sort of yarn problem?

**To Reproduce**
1. Install fresh copy of Ubuntu server
2. git clone shash-box
3. use the instruction and fail

**Expected behavior**
I would expect for the project to be built and, well, the instructions were unclear, so I don't really know what to expect and how to run it afterwards, but I assume the aforementioned errors are not the desired result.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 running in a qemu vm

**Comment by WithoutPants** [comment]
Looks to me like your yarn version is old perhaps?

**Comment by DJ73** [comment]
I was able to setup yarn and run the first two steps but when I run `make ui build`, the first part works but then I encounter this error and I don't know where to begin
```
packr2
process_begin: CreateProcess(NULL, packr2, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:115: ui] Error 2
```

Edit: I'm on Windows 10 btw
