### ISSUE TITLE
[Feature] Aliases association with studio

### ISSUE THREAD

**Issue by ghost** [stashapp/stash-box#545]
**Is your feature request related to a problem? Please describe.**
Each performer alias should be associated to a studio or string to specify its origin.
This would allow searching by name and studio, helping imensly with single name performers.

**Describe the solution you'd like**
New performer alias structure :
From
` List<String>`
To
` List<Alias>`
Where 
Alias : `List<Dict<String(aliasLabel) , StudioID | String(In the case of none studio sources>>`

**Comment by peolic** [comment]
Sounds similar to #335

**Comment by ghost** [comment]
True. Closing
