### ISSUE TITLE
[Feature] Filter for scenes including favorite performers on performer site

### ISSUE THREAD

**Issue by whadup93** [stashapp/stash-box#565]
Sometimes it would be convenient to show only scenes of a specific performer which include favorite performers. Right now it is only possible to filter for **favorite studios** at a performer's site. It **is** actually already possible to filter for favorite performers but only at a **studio's page**. 

So what I have in mind is something like this:

![image](https://user-images.githubusercontent.com/66875432/204102730-1ca94ca5-a1f6-4631-bac9-f85acace8a67.png)

**Comment by xiosensei** [comment]
Instead of this, I think a scene search page where someone can choose the performers, studios, and tags would be a better feature.

**Comment by DogmaDragon** [comment]
Implemented via Scene Pairings which can then be further filtered by favorites. 
![image](https://github.com/user-attachments/assets/15700090-c4a8-460e-bf6e-51a8c427b231)
