### ISSUE TITLE
[Bug Report] Doesn't detect the change when any field is changed to null

### ISSUE THREAD

**Issue by DogmaDragon** [stashapp/stash-box#587]
**Describe the bug**
stash-box doesn't detect the change when the Network field is changed to null. 

**To Reproduce**
1. Go to https://stashdb.org/studios/975ac356-169d-4d0f-b22e-8df2769e5846
2. Click on `Edit`.
3. Remove `Network`.
4. Navigate to the `Confirm` tab and click `Submit Edit`.
5. Get error `Error: edit contains no changes`.

**Expected behavior**
Existing Network being removed and the value changed to null.

**Screenshots**
![ede9e821-fc54-49c5-a01e-92513bb3842e](https://user-images.githubusercontent.com/103123951/212426308-d605dff5-fca2-47e4-b2c1-0166743097d5.png)

**Comment by nrg101** [comment]
![remove-network-edit-does-not-work](https://user-images.githubusercontent.com/37197306/215124453-077c9ab6-36fc-477f-8bc1-347b5da8ffbc.png)

I also experience this problem, browser console shows

```
[GraphQL error]: Message: edit contains no changes, Location: undefined, Path: studioEdit
```

and it looks like maybe the `variables.studioData.details` in the graphql should contain `"parent": null` but it doesn't have any mention of `parent` (that is mentioned further down in the graphql)

**Comment by DogmaDragon** [comment]
Doesn't seem to be Network only issue, but any field.

**Comment by Flashy78** [comment]
I could only seem to reproduce this for removing Network from Studio.
It looks like @nrg101 assessment is correct. Instead of passing in a null value, it's just not passing a value, which the backend code assumes means to ignore that field and not change it. Unfortunately not very well versed in React, so couldn't figure out how to make the Async Select box set an empty value when it has nothing in it.

**Comment by ghost** [comment]
> I could only seem to reproduce this for removing Network from Studio. It looks like @nrg101 assessment is correct.

I was able to reproduce when I went to remove the disambiguation from this performer.
https://stashdb.org/performers/083e564f-9c04-4c39-a425-7641e393a595

**Comment by Maista6969** [comment]
Can confirm this was broken in https://github.com/stashapp/stash-box/commit/d64783e4efbd783b349fb57c8d3ac52bd65053fb
