### ISSUE TITLE
[Feature] Ability to abstan vote as 1st vote

### ISSUE THREAD

**Issue by PhuriousGeorge** [stashapp/stash-box#588]
**Is your feature request related to a problem? Please describe.**
Currently users only have the option to `Abstain` and click `Save` after they've voted `Yes` or `No`.  With the recent addition of user vote-filtering (look ma, my queue's clean!) and the only initial offerings of Yes/No, this pressures a user toward making a binary vote when maybe they should pass.

**Describe the solution you'd like**
Allow users to select `Abstan` from the onset

**Describe alternatives you've considered**
Personally I vote `No` then change to `Abstain`, but I'm not normal and typical people take the path of least resistance

**Comment by DogmaDragon** [comment]
I don't think filtering has a lot to do with the mass `Yes` voting, it's been happening long before we were able to filter by votes. And while I don't see any possible harm this change would cause, I don't think it would solve the underlying issue of people voting `Yes` without checking.

And maybe it's just me I feel like a change from `No` to `Abstain` makes no sense if the user fixed the issue you had that made you vote `No` in the first place. Why not just change it to `Yes`? `Abstain` for me is the edge case where you disagree with something undefined in the guidelines, but don't want to hold up the submission once you hear different arguments from other people.

**Comment by PhuriousGeorge** [comment]
I agree this won't _solve_ the underlying issue, but from other crowdsourced data projects I've been involved in I know now that the plate can be cleared, there are those that are motivated to do so and could be influenced.

As to the personal `No`/`Abstain` example of how I currently operate, You have to vote `Yes` or `No` to `Abstain`.  I choose to default `No` so I don't accidently pass something by choosing `Yes`.  The whole purpose is to get to `Abstain` so I can stop tripping over the same items that either I have no experience with and will therefore require a lot of effort, or content I just don't want to see (at all or at that time) or be bothered with when queues reach >1000 there's plenty of other items I can be more beneficial working.  Sometimes I choose to filter to `Abstain` later when I'm ready

**Comment by Flashy78** [comment]
Looks like just removing this check will allow Abstain to be a valid first vote option.
https://github.com/stashapp/stash-box/blob/master/frontend/src/components/editCard/VoteBar.tsx#L67

**Comment by WithoutPants** [comment]
If this is primary to solve an issue with the queue-like behaviour, I'd prefer an explicit `Skip` or `Ignore` button, which when pressed marks the edit as skip/ignored. These edits will not be shown by default, with an flag to show them if needed.

The Abstain button should also not be displayed if the user hasn't already voted. This way, it is clear to the user that they can skip an edit, and thus presumably are less likely to make invalid votes.
