### ISSUE TITLE
[Feature] Url display / editing for performers

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash-box#59]
**Is your feature request related to a problem? Please describe.**
Performer url's are in the database and in the graphql api but are not currently displayed or available to edit. 

**Describe the solution you'd like**
On the performer page display a list of url's associated with the performer.
Update the edit performer pages and have a way to add a list of url's to the performer.

The graphql api will return a list of url's for the performer and will allow you to edit a performer and add a list of url's.
We just need a way of displaying and editing this information.

**Comment by peolic** [comment]
Implemented in #140.
