### ISSUE TITLE
[Feature] Allow Multiple Edits and Reset Votes

### ISSUE THREAD

**Issue by Flashy78** [stashapp/stash-box#593]
One issue that keeps frustrating users is that they can only edit their submissions once. This is most often seen with new contributors who often need guidance with their submissions before they learn the ropes. They can get discouraged because their submission was downvoted because they could only make the first suggested change to it, or they have to cancel their submission and re-do their effort.

It was mentioned in https://github.com/stashapp/stash-box/issues/226 that users should be limited to a single edit to prevent abuse. The assumption is that this was because votes are not reset when an edit is updated.

I propose changing it so that previous votes are no longer counted when an edit is updated, and the limit on the number of updates is removed.

**Updated Implementation Ideas**

Thought about it more and I think it's just best to do the filtering in the database without trying to hack it. That makes it consistent and will work for other voting queries such as the user voted filtering.

**Initial Implementation Ideas**

Modify https://github.com/stashapp/stash-box/blob/master/pkg/api/resolver_model_edit.go#L314 to filter out votes cast after the `updated` time. This makes it easy on the database queries by not introducing filtering on the large `edit_votes` table, and the amount of votes for an edit shouldn't be that large that filtering in code has any negative affect.
However if a user is sitting on the edit queue webpage and hasn't refreshed in a while, they may not get the latest changes to an edit when they submit their vote and it could be counted towards the updated version.
On the frontend it complicates the Votes section of an edit. With the above approach, it would only show votes for the current update. Maybe a second section could be added showing previous votes. 

This also complicates the user voted filter, as they could have previously voted on an edit, but the updated edit should show as if they haven't voted yet. Not sure how to handle this, it may make the approach above with filtering in code not viable.

Thoughts and suggestions?

**Comment by Flashy78** [comment]
Thought about it more and I think it's just best to do the filtering in the database without trying to hack it. That makes it consistent and will work for other voting queries such as the user voted filtering.

**Comment by AdultSun** [comment]
Resetting votes after an update makes perfect sense to me, I was confused when that wasn't already part of the initial implementation. I remember that being part of the original design. In the current build, I think the countdown timer can sometimes reset after an update though? I'm not sure, it's rarely relevant enough for me to notice and only seems to happen in certain situations.

I can also see how the resetting of votes would mitigate the risk for abuse and reduce the need to limit it to one update per submission. I'm not sure if removing that limit entirely would be best though, unlimited updates seems like overkill to me. Even a 3 update max could be enough for 99% of submissions.

Also I don't know if the timers will be reset after an update but unlimited updates plus reset timers means you could theoretically have an edit that gets stuck in the queue forever. If that timer keeps resetting then the edit will never expire into an approval or rejection. While obviously that scenario is unrealistic, it does show how a troll could continually "misunderstand" update requests and keep a single edit alive as long as they update it before getting 3 unanimous NO votes, wasting everyone's time until an admin steps in to unilaterally reject it.

**Comment by Flashy78** [comment]
Thank you for thinking about this.
From what I can see in the code, the countdown timer should always start over when an update happens. So after this change, that troll scenario would be possible.
Unfortunately it's currently hardcoded to stop a user if the `updated_at` field has a value.  It's not where I could change a 1 to a 10 and allow 10 edits. So implementing a configurable limit would be a good more work. I think I would rather leave that as a future feature to implement in response to a need.

**Comment by ghost** [comment]
That is a case that would present rarely and the moderator could instantly accept and be done with it.
