### ISSUE TITLE
RenameOnUpdate

### ISSUE THREAD

**Issue by Haezer89** [stashapp/stash-box#604]
##  Long Form

Hey Guys, 
I am a little bit stuck at this plugin and don`t get it to work. Did anyone using it in a Docker Container and have it successfully running?
Already have problems with the logfile because of the path or something. Tried already a lot of variations. How to achieve this for example?

Thank you in Advance

**Comment by DogmaDragon** [comment]
Wrong repository. Post in <https://github.com/stashapp/CommunityScripts> or join community Discord for help <https://discord.gg/2TsNFKt>.
