### ISSUE TITLE
[Bug Report] Cannot remove "Career End" on performer

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash-box#617]
**Describe the bug**
You are currently unable to remove the "Career End" field on a performer. If it's the only field being changed, it will throw an error, if you're changing other fields, the "Career End" change won't be submitted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any performer that has their "Career End" set.
2. Edit the performer and _only_ remove the "Career End" value.
3. Go to save the edit.
4. "Error: edit contains no changes"

**Expected behaviour**
You should be allowed to remove the "Career End" value. Sometimes they're set erroneously or a performer may return.

**Screenshots**
![image](https://user-images.githubusercontent.com/68614336/222290177-4b427f87-fc34-4003-8a18-0622bce32d7c.png)

**Comment by DogmaDragon** [comment]
Dupe of https://github.com/stashapp/stash-box/issues/587
