### ISSUE TITLE
[Feature] Version note

### ISSUE THREAD

**Issue by DogmaDragon** [stashapp/stash-box#642]
**Is your feature request related to a problem? Please describe.**
With other stash-box instances becoming available it would be nice to know which version they are running, since it's unlikely they will all update at the same time. 

**Describe the solution you'd like**
Adding a version note with release tag or commit hash somewhere on the frontend.

**Comment by AdultSun** [comment]
It's not easily found, but we already have this:
https://stashdb.org/version
