### ISSUE TITLE
[Feature] Add Alias or Scene code field to StashDB for studios

### ISSUE THREAD

**Issue by itanameiguess** [stashapp/stash-box#707]
**Is your feature request related to a problem? Please describe.**
Almost all JAV studios, and some others, always release their scenes with a short letter code as the title, being able to search that code to find the studio or help identify which studio a scene should be under would assist in easier scene submission

**Describe the solution you'd like**
An Alias field for studios, like currently exists within Stash, or a dedicated field for "studio codes", i.e., Wanz Factory releases all scenes as WANZ-123 or WAAA-123, so being able to add WANZ and WAAA to the studio in some form would be helpful information, not all studio's have as obvious codes related to their studio

**Describe alternatives you've considered**
feature isn't critical for StashDB, but would bring feature parity to Stash, and could assist in some edge cases, and heavily in JAV content

**Comment by InfiniteStash** [comment]
@itanameiguess Scenes already support studio codes. You can search for them as well, e.g. `LAFBD-46`. Is that sufficient, or was there something else you had in mind?

**Comment by DogmaDragon** [comment]
I think it was more of request for studio aliases. Just the described use case was to use universal studio codes as part of the alias.

**Comment by MyDirtyAccount** [comment]
This overlaps with #676
