### ISSUE TITLE
[RFC] API Documention for HTTP Upload

### ISSUE THREAD

**Issue by hydrian** [stashapp/stash-box#740]
# API content upload documentation

### Scope
I'm looking into creating a Flutter app to let mobile clients upload content to their stash server. 

##  Long Form
Many times I'd love to just easily 'share' a downloaded image/video file directly to my stash server. I haven't seen any work like this currently. I'm a beginner flutter dev and this doesn't look like it is out of my abilities. I'm looking for any documentation on the HTTP API call that would be needed for my app. 

## Examples
TBD

**Comment by DogmaDragon** [comment]
It's all GraphQL. Schema is available at https://github.com/stashapp/stash/tree/develop/graphql. You can also browse it via `HOST:PORT/playground` e.g., `localhost:9999`.

EDIT: I think you meant to submit  this RFC to [Stash repo](https://github.com/stashapp/stash), not this one. stash-box doesn't store any content, just metadata.

**Comment by hydrian** [comment]
@DogmaDragon Thank you! I wasn't sure if the API call I needed was the slash repo or the stash-box repo. Thanks for clarifying for me.
