### ISSUE TITLE
[Feature] Upload multiple scene URLs

### ISSUE THREAD

**Issue by Eleniatari** [stashapp/stash-box#741]
**Is your feature request related to a problem? Please describe.**
The inability to upload more then the studio link results in links being forgotten or not unloaded when working primarily in a local database.

**Describe the solution you'd like**
All links in the local instance being uploaded when uploading a scene.

**Describe alternatives you've considered**
Do nothing different then as is.

**Additional context**
I often forget to go back and migrate links, I work in batches, cross referencing all scenes to multiple sources in order to guarantee proper performer references and submit all as pending edits. Unless I remember to specifically go back and transfer them in extra steps I forget it.

**Comment by dingdongsolong4** [comment]
The plumbing on the stash side is all there - all that stash-box needs to do is allow for multiple URLs in `SceneDraft` and `SceneDraftInput`.

**Comment by UltraHKR** [comment]
A further enhancement is to grab PornDB id's if the scene is tagged as well...

**Comment by S3L3CT3DLoves** [comment]
I've been trying to implement this, and it poses one question. Right now when submitting a Scene, if the link does not match any of the other sites, it automatically gets assigned the "Studio" site as a default.

If we replicate this, it will create a mess. Studio links are meant to be highly trusted based on my understanding. So using it as a "default" link type for any link that doesn't match the other site regexes doesn't make sense.

As discussed on Discord, I see two options:
1. Match the sites in the backend, and accept the problem of having many Studio sites that are not actually Studio sites.
2. Match the sites in the frontend, and ask the user to add the links manually if they don't match a valid Site type  (this is what is done for Performers)

So I'm going to go with Option 2, unless we find a better one.

**Comment by S3L3CT3DLoves** [comment]
> A further enhancement is to grab PornDB id's if the scene is tagged as well...

This would need to happen in Stash, not StashBox.
