### ISSUE TITLE
[Enhancement] Allow multiple Data18 entries on stashdb server

### ISSUE THREAD

**Issue by UltraHKR** [stashapp/stash-box#747]
Describe the problem
The stashdb server is unable to save multiple Data18 entries... I hit this limitation

Describe the solution you'd like
Allow multiple entries like a local stash instance.

Describe alternatives you've considered
Spam the comment box with metadata, when submitting scenes...

**Comment by AdultSun** [comment]
I can't replicate this bug, so I'm closing the issue for now. I don't believe Stash-Box limits the number of links you can add under a single "category" like Data18. However it will prevent users from adding duplicate links if the URLs are exactly the same, so maybe you ran into that without realizing a duplicate URL was still in your clipboard.

I opened a scene edit form to double-check and I was able to add both Data18 links:
![image](https://github.com/stashapp/stash-box/assets/64123896/1675f145-b462-4318-a313-f551354c1855)
