### ISSUE TITLE
[Feature] Multi Object Edits

### ISSUE THREAD

**Issue by stg-annon** [stashapp/stash-box#821]
**Is your feature request related to a problem? Please describe.**
There is a common where a scene might have a one off performer, the process for adding such a scene is annoying as you first have to create the one off performer in stash-box then wait for the edits to pass then create the scenes and add the new performer.

**Describe the solution you'd like**
Ideally we could create the new performer and scene in the same edit and both would pass/fail based off that edits votes

**Comment by DogmaDragon** [comment]
Duplicate of https://github.com/stashapp/stash-box/issues/627
