### ISSUE TITLE
`0th revision` on edits updated prior to #844

### ISSUE THREAD

**Issue by peolic** [stashapp/stash-box#874]
This is on develop.

To prevent `0th revision`, it may be useful to set `update_count = 1` when `updated_at IS NOT NULL` during the migration added in #844.

![image](https://github.com/user-attachments/assets/0da765ef-0c35-47c0-a038-b9abe4eaabae)

https://github.com/stashapp/stash-box/blob/2a063aebfa9cc8eff48bf728385f9f1b8987cefc/pkg/database/migrations/postgres/39_edits_updates.up.sql#L1-L2

**Comment by InfiniteStash** [comment]
Good catch, thanks!
