### ISSUE TITLE
[RFC] Fingerprint submission changes

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash-box#99]
# Problem

The current fingerprint submissions system is prone to bad data which involves manual labour to remove. This stems from the fingerprint `submissions` field being a simple counter which is incremented whenever a user matches it. Removing bad matches currently requires manually removing the entry.

# Proposal

Fingerprints submissions should be related to the user that submitted them, and a user can only pair a fingerprint hash to a single scene. That is, if they re-submit the same hash to a different scene, then the original user/fingerprint/scene relationship will be removed in favour of the new one. The `submissions` field will then be a resolver of a count of total submissions in the database. From what I can tell, the existing `submissions` field isn't actually maintained.

Querying for scenes by fingerprint may return multiple candidates, and we should allow for this in the graphql schema and in the client tagger view. Obviously, the best match (ie the one with the highest submission count) should be displayed first, but other candidates should be available in case the first is not the correct match. If a user currently has a scene matched, then they should be able to unmatch it manually, as an alternative to matching it to another scene (in the event that an alternative scene does not exist).

# Impacts

The one-scene-per-hash change will have impacts on the shared test account we currently have.

In order to maintain our existing fingerprint data, we will want to migrate it to link it with a specially created internal user.

# Other considerations

I don't think that it's necessary to have a report or down-vote et al function for scene fingerprints. I believe that bad matches will tend toward the zero count, and good matches will inevitably tend upwards. When a user finds a bad match, they can unmatch on there system if necessary, and manually look for an alternative scene and match that as needed.

To reduce useless or bad data, we should consider automating the removal of single count fingerprints that are older than a configurable age. This will reduce storage overhead.

I'm not sure what use `duration` will be when moving toward this new mechanism. We should be using the "official" duration for match validation in the client. Submitting clips or compilations from a single scene should also be encouraged, so the duration may not necessarily match. 

# Implementation details

## Database schema

In `scene_fingerprints`:
* deprecate `duration` and `submissions`
* remove `updated_at`
* add `user_id uuid`
* add indexes on `user_id`, `scene_id` and `created_at`

## Graphql schema

* add `unmatch` boolean flag to `FingerprintSubmission`. When true, this will unmatch the scene from the fingerprint for the current user, if present.
* deprecate `duration` from `Fingerprint` and related objects - make it optional.
* add `limit` and `offset` to `FingerprintQueryInput` to designate the maximum number of matches to return and the offset. This means that a client can get the top match(es) and alternative matches as needed.
* `findSceneByFingerprint` should return `QueryScenesResultType`, or some intermediate type to prevent breaking changes. The main purpose is so the client can get the total number of matching scenes for a single fingerprint.
* likewise, `findScenesBy[Full]Fingerprints` should return an array of `QueryScenesResultType`, or some intermediate type to prevent breaking changes.
* `fingerprints` should probably be deprecated from `Scene` (and return an empty list) in favour of a query interface. The number of fingerprints could potentially get quite large.

**Comment by ferengi82** [comment]
my 2 cents:

- i'm not sure if its possible to reduce 1 phash = 1 scene, there are many scene which are used on different sites and have the same has
- if possible integrate a "weight" for submitted hashes (if someone searches for a scene by name and tags it = 100 points, if some one only search for phash and submits blindly = 10 points ...)

**Comment by ghost** [comment]
> Fingerprints submissions should be related to the user that submitted them, and a user can only pair a fingerprint hash to a single scene.

This would be ideal from a data perspective, but it does mean users handing over library data to the stash-box instance. Even though it won't be public, I can imagine some users being reticent about doing that. There are certainly a lot of advantages though.

> Querying for scenes by fingerprint may return multiple candidates, and we should allow for this in the graphql schema and in the client tagger view.

I think this is already the case.

> If a user currently has a scene matched, then they should be able to unmatch it manually, as an alternative to matching it to another scene (in the event that an alternative scene does not exist).

This would require storing the submission status in the client db. I think this is probably the way to go anyway though since storing submissions in localStorage is bad in a lot of ways.

>  I believe that bad matches will tend toward the zero count, and good matches will inevitably tend upwards.

I'm not so certain about that. The typical bad match scenario is that a scene is missing from the db, and another scene has the same performer with a similar studio/scene title. Once one bad fingerprint is matched that causes more of them to get piled on since people assume fingerprint matches are correct. We would have to highlight "split" fingerprints to the user somehow so they were actually encouraged to reconsider, otherwise I'm afraid most users won't revisit the bad match.

> I'm not sure what use duration will be when moving toward this new mechanism. We should be using the "official" duration for match validation in the client. 

Fingerprint durations are incredibly useful to recognizing bad matches, and also allows us to extrapolate official durations when they're missing in the data. While it does lead to some degree of data duplication, I think that's a relatively small trade-off.

**Comment by WithoutPants** [comment]
I'm happy to leave duration in there, though it means that the duration resolver needs to determine the current value to use. I've gone with `AVG` at the moment, but I'm not sure if there's a more appropriate aggregate function to use.

Looking at the way that the scene creation and update mutators work, I'm thinking that we should remove the fingerprint setting functionality from these, and use a separate (`modify`-role-only) `SubmitFingerprints` mutator to match/unmatch multiple fingerprints instead. `SubmitFingerprint` would remain the interface for normal users to match/unmatch their personal fingerprints.

**Comment by WithoutPants** [comment]
> * i'm not sure if its possible to reduce 1 phash = 1 scene, there are many scene which are used on different sites and have the same has

Having thought on this further, I think restricting 1-to-1 hash-to-scene for a user is going to be limiting. There are cases where a single file is going to contain multiple scenes. Until we have a better way to handle split scenes in a single file, I think allowing multiple relationships for a user will offer us better flexibility.
